import React from "react";
import Barcode from 'react-barcode';
import { QRCodeCanvas } from 'qrcode.react'; // or use QRCodeSVG


const EWayBill = ({ billData }) => {
  const {
    docType = "Not Provided",
    docNo = "Not Provided",
    docDate = "Not Provided",
    fromGstin = "Not Provided",
    fromTrdName = "Not Provided",
    fromAddr1 = "Not Provided",
    fromAddr2 = "Not Provided",
    fromPlace = "Not Provided",
    fromPincode = "Not Provided",
    toGstin = "Not Provided",
    toTrdName = "Not Provided",
    toAddr1 = "Not Provided",
    toAddr2 = "Not Provided",
    toPlace = "Not Provided",
    toPincode = "Not Provided",
    totalValue = "Not Provided",
    cgstValue = "Not Provided",
    sgstValue = "Not Provided",
    igstValue = "Not Provided",
    cessValue = "Not Provided",
    cessNonAdvolValue = "Not Provided",
    totInvValue = "Not Provided",
    transMode = "Not Provided",
    transDistance = "Not Provided",
    transporterName = "Not Provided",
    transporterId = "Not Provided",
    transDocNo = "Not Provided",
    transDocDate = "Not Provided",
    vehicleNo = "Not Provided",
    vehicleType = "Not Provided",
    itemList = [],
    ewayBillNo = "Not Provided",
    generatedDate = "Not Provided",
    generatedBy = "Not Provided",
    validUpto = "Not Provided",
    otherValue = "Not Provided",
    transactionTypeDesc = "Not Provided",
  } = billData;
  const qrCodeValue = `eWay Bill No: ${ewayBillNo || "N/A"}, Validity Time: ${billData.validity_time || "N/A"}, Generated Time: ${billData.generated_time || "N/A"}`;

  return (
<div className="w-210mm h-297mm">
    <div className="mx-5 my-5 p-5 bg-white shadow-lg rounded-lg border">
    <div className="flex items-center justify-between mb-4 h-4">
  <h1 className="font-bold mt-4 mb-2 text-lg">E-Way Bill</h1>
  <div className="flex flex-col items-center">
  <QRCodeCanvas 
  value={qrCodeValue} 
  style={{ 
    width: '3rem', 
    height: '3rem', 
    margin: '0.5rem',
    padding:'0.25rem'
  }} 
/>
  </div>
</div>
<div className="border border-gray-300 mb-4"> {/* Reduced margin-bottom */}
  <h1 className="bg-[#736fb3] text-black p-1 text-sm"> {/* Reduced padding and font size */}
    1. E-WAY BILL Details
  </h1>

  <div className="p-1 border flex flex-col sm:flex-row justify-between text-sm"> {/* Adjusted padding and layout */}
  <div className="flex flex-col sm:flex-row">
    <p className="mb-2 sm:mb-0">
      <span className="font-normal">eWay Bill No:</span>{" "}
      <span className="font-bold">{ewayBillNo || "N/A"}</span>
    </p>
    <p className="mb-2 sm:mb-0 sm:ml-4">
      <span className="font-normal">Generated Date:</span>{" "}
      <span className="font-bold">{generatedDate || "N/A"}</span>
    </p>
  </div>
  <div className="flex flex-col">
    <p className="mb-2">
      <span className="font-normal">Generated By:</span>{" "}
      <span className="font-bold">{generatedBy || "N/A"}</span>
    </p>
    <p>
      <span className="font-normal">Valid Upto:</span>{" "}
      <span className="font-bold">{validUpto || "N/A"}</span>
    </p>
  </div>
</div>


<div className="p-1 border flex justify-between text-sm"> {/* Adjusted padding */}
  <p>
    <span className="font-normal">Mode:</span>{" "}
    <span className="font-bold">{transMode || "N/A"}</span>
  </p>
  <p className="text-left">
    <span className="font-normal">Approx Distance:</span>{" "}
    <span className="font-bold">{transDistance || "N/A"}</span>
  </p>
  
</div>


<div className="p-1 border flex justify-between text-sm"> {/* Adjusted padding */}
  <p className="flex-1">
    <span className="font-normal">Type:</span>{" "}
    <span className="font-bold">{transactionTypeDesc || "N/A"}</span>
  </p>
  <p className="flex-1 text-left"> {/* Centered text for better alignment */}
    <span className="font-normal">Document Details:</span>{" "}
    <span className="font-bold">
      {docType} - {docNo} - {docDate}
    </span>
  </p>
  <p className="flex-1 text-right"> {/* Right-aligned text */}
    <span className="font-normal">Transaction Type:</span>{" "}
    <span className="font-bold">{transactionTypeDesc || "N/A"}</span>
  </p>
</div>

</div>


      <h4 className="bg-[#736fb3] text-black text-sm p-2 mb-1">
        2. Address Details
      </h4>
      <div className="flex justify-between mb-4"> {/* Reduced bottom margin */}
  {/* From Details Section */}
  <div className="w-1/2 border border-gray-300 bg-white mr-2"> {/* Added border color and adjusted margin */}
    <h2 className="bg-[#736fb3] text-black p-1 text-sm"> {/* Reduced padding and font size */}
      From
    </h2>
    <div className="p-2 text-sm"> {/* Reduced padding and font size */}
      <p>
        <span className="font-normal">GSTIN: </span>{" "}
        <span className="font-bold">{fromGstin || "N/A"}</span>
      </p>
      <p>
        <span className="font-normal">{fromTrdName || "N/A"}</span>
      </p>
      <br />

      <p className="font-normal">:: Dispatch From ::</p>
      <p>
        <span className="font-normal">
          {fromAddr1}, <br />
          {fromAddr2}, {fromPlace}, {fromPincode}
        </span>
      </p>
    </div>
  </div>

  {/* To Details Section */}
  <div className="w-1/2 border border-gray-300 bg-white flex-1"> {/* Adjusted border and flex properties */}
    <h2 className="bg-[#736fb3] text-black p-1 text-sm"> {/* Reduced padding and font size */}
      To
    </h2>
    <div className="p-2 text-sm"> {/* Reduced padding and font size */}
      <p>
        <span className="font-normal">GSTIN: </span>{" "}
        <span className="font-bold">{toGstin || "N/A"}</span>
      </p>
      <p>
        <span className="font-normal">{toTrdName || "N/A"}</span>
      </p>
      <br />

      <p className="font-normal">:: Shipped From ::</p>
      <p>
        <span className="font-normal">
          {toAddr1}, <br />
          {toAddr2}, {toPlace}, {toPincode}
        </span>
      </p>
    </div>
  </div>
</div>


      <div className="border border-gray-300 pt-0 mb-5 bg-white">
        <h2 className="bg-[#736fb3] text-black font-semibold p-2 text-sm">
          3. Goods Details
        </h2>
        
        <table className="w-full border-collapse mt-2 text-sm"> {/* Reduced top margin and font size */}
  <thead>
    <tr>
      <th className="border border-gray-300 p-1">HSN</th> {/* Reduced padding */}
      <th className="border border-gray-300 p-1">Product & Desc.</th> {/* Shortened header text */}
      <th className="border border-gray-300 p-1">Quantity</th>
      <th className="border border-gray-300 p-1">Taxable Amount</th> {/* Shortened header text */}
      <th className="border border-gray-300 p-1">Tax Rate (C+S+I+Cess)</th> {/* Shortened header text */}
    </tr>
  </thead>
  <tbody>
    {itemList.map((item, index) => (
      <tr key={index}>
        <td className="border border-gray-300 p-1 text-center"> {/* Reduced padding */}
          {item.hsnCode || "N/A"}
        </td>
        <td className="border border-gray-300 p-1 text-center"> {/* Reduced padding */}
          {item.productName || "N/A"} & {item.productDesc || "N/A"}
        </td>
        <td className="border border-gray-300 p-1 text-center"> {/* Reduced padding */}
          {item.quantity || "N/A"} {item.qtyUnit || "N/A"}
        </td>
        <td className="border border-gray-300 p-1 text-center"> {/* Reduced padding */}
          {item.taxableAmount || "N/A"}
        </td>
        <td className="border border-gray-300 p-1 text-center"> {/* Reduced padding */}
          {item.sgstRate || "N/A"} + {item.cgstRate || "N/A"} + {item.igstRate || "N/A"} + {item.cessRate || "N/A"}
        </td>
      </tr>
    ))}
  </tbody>
</table>

<table className="w-full border-collapse mt-4 text-sm"> {/* Reduced top margin and font size */}
  <thead>
    <tr>
      <th className="border border-gray-300 p-1">Tot. Taxable Amt</th> {/* Reduced padding */}
      <th className="border border-gray-300 p-1">CGST Amt</th>
      <th className="border border-gray-300 p-1">SGST Amt</th>
      <th className="border border-gray-300 p-1">IGST Amt</th>
      <th className="border border-gray-300 p-1">CESS Amt</th>
      <th className="border border-gray-300 p-1">CESS Non.Advol Amt</th>
      <th className="border border-gray-300 p-1">Other Amt</th>
      <th className="border border-gray-300 p-1">Total Inv. Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td className="border border-gray-300 p-1 text-center"> {/* Reduced padding */}
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {totalValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {cgstValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {sgstValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {igstValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {cessValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {cessNonAdvolValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {otherValue || "N/A"}
        </div>
      </td>
      <td className="border border-gray-300 p-1 text-center">
        <div className="p-1 border border-gray-300 bg-white rounded"> {/* Reduced padding */}
          {totInvValue || "N/A"}
        </div>
      </td>
    </tr>
  </tbody>
</table>

      </div>

      <div className="border border-gray-300 mb-4 bg-white"> {/* Reduced bottom margin */}
  <h2 className="bg-[#736fb3] text-black font-semibold p-1 text-base"> {/* Reduced padding and font size */}
    4. Transportation Details
  </h2>

  <div className="flex flex-row justify-between p-2 space-y-1"> {/* Changed to justify-between for left and right alignment */}
  <div className="flex items-center text-sm"> {/* Smaller font size */}
    <span className="font-normal mr-2">Transporter ID & Name:</span>
    <span className="font-normal">
      {transporterName || "N/A"}, {transporterId || "N/A"}
    </span>
  </div>
  <div className="flex items-center text-sm"> {/* Smaller font size */}
    <span className="font-normal mr-2">Transporter Doc. No & Date:</span>
    <span className="font-normal">
      {transDocNo || "N/A"}, {transDocDate || "N/A"}
    </span>
  </div>
</div>

</div>


      <div className="border border-gray-300 bg-white mb-5">
        <h2 className="bg-[#736fb3] text-black font-semibold p-2 text-sm">
          5. Vehicle Details
        </h2>
        <table className="w-full border-collapse mt-2 text-sm">
  <thead>
    <tr>
      <th className="border border-gray-300 px-1 py-1">Mode</th>
      <th className="border border-gray-300 px-1 py-1">
        Vehicle / Trans Doc No & Dt.
      </th>
      <th className="border border-gray-300 px-1 py-1">From</th>
      <th className="border border-gray-300 px-1 py-1">Entered Date</th>
      <th className="border border-gray-300 px-1 py-1">
        Entered By
      </th>
      <th className="border border-gray-300 px-1 py-1">CEWB No. (if any)</th>
      <th className="border border-gray-300 px-1 py-1">Multi Veh.Info (if any) </th>
    </tr>
  </thead>
  <tbody>
    {itemList.map((item, index) => (
      <tr key={index}>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {transMode || "Not Provided"}
        </td>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {vehicleNo || "Not Provided"} &{" "}
          {vehicleType || "Not Provided"}
        </td>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {fromAddr1 || "Not Provided"}{" "}
        </td>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {generatedDate || "Not Provided"}
        </td>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {generatedBy || "Not Provided"}
        </td>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {"-" || "Not Provided"}
        </td>
        <td className="border border-gray-300 px-1 py-1 text-center">
          {"-" || "Not Provided"}
        </td>
      </tr>
    ))}
  </tbody>
</table>

<div className="flex justify-center items-center">
  <Barcode value={ewayBillNo || "N/A"} className="w-48 h-24" />
</div>



Note*: If there is any discrepancy in information please try again after sometime.

      </div>
    </div>
    </div>
  );


};

export default EWayBill;
