import React from "react";
import Barcode from 'react-barcode';
import { QRCodeCanvas } from 'qrcode.react';
import './EWayBill.css'; 
const EWayBill = ({ billData }) => {
  const {
    docType = "Not Provided",
    docNo = "Not Provided",
    docDate = "Not Provided",
    fromGstin = "Not Provided",
    fromTrdName = "Not Provided",
    fromAddr1 = "Not Provided",
    fromAddr2 = "Not Provided",
    fromPlace = "Not Provided",
    fromPincode = "Not Provided",
    toGstin = "Not Provided",
    toTrdName = "Not Provided",
    toAddr1 = "Not Provided",
    toAddr2 = "Not Provided",
    toPlace = "Not Provided",
    toPincode = "Not Provided",
    totalValue = "Not Provided",
    cgstValue = "Not Provided",
    sgstValue = "Not Provided",
    igstValue = "Not Provided",
    cessValue = "Not Provided",
    cessNonAdvolValue = "Not Provided",
    totInvValue = "Not Provided",
    transMode = "Not Provided",
    transDistance = "Not Provided",
    transporterName = "Not Provided",
    transporterId = "Not Provided",
    transDocNo = "Not Provided",
    transDocDate = "Not Provided",
    vehicleNo = "Not Provided",
    vehicleType = "Not Provided",
    itemList = [],
    ewayBillNo = "Not Provided",
    generatedDate = "Not Provided",
    generatedBy = "Not Provided",
    validUpto = "Not Provided",
    otherValue = "Not Provided",
    transactionTypeDesc = "Not Provided",
  } = billData;
  const qrCodeValue = `eWay Bill No: ${ewayBillNo || "N/A"}, Validity Time: ${billData.validity_time || "N/A"}, Generated Time: ${billData.generated_time || "N/A"}`;

  return (
    <div className="container">
      <div className="mb-4">
        <div className="flex-row">
          <h1 className="bold">E-Way Bill</h1>
          <div className="center">
            <QRCodeCanvas value={qrCodeValue} className="qrcode" />
          </div>
        </div>
        <div className="border-box">
          <h1 className="header">1. E-WAY BILL Details</h1>
          <div className="flex-row">
            <div className="flex-column">
              <p className="normal">eWay Bill No: <span className="bold">{ewayBillNo}</span></p>
              <p className="normal">Generated Date: <span className="bold">{generatedDate}</span></p>
            </div>
            <div className="flex-column">
              <p className="normal">Generated By: <span className="bold">{generatedBy}</span></p>
              <p className="normal">Valid Upto: <span className="bold">{validUpto}</span></p>
            </div>
          </div>
        </div>

        <div className="border-box">
          <h4 className="address-header">2. Address Details</h4>
          <div className="flex-row">
            <div className="flex-1 border-box">
              <h2 className="header">From</h2>
              <p className="normal">GSTIN: <span className="bold">{fromGstin}</span></p>
              <p className="normal">{fromTrdName}</p>
              <p className="normal">:: Dispatch From ::</p>
              <p className="normal">{fromAddr1}, {fromAddr2}, {fromPlace}, {fromPincode}</p>
            </div>
            <div className="flex-1 border-box">
              <h2 className="header">To</h2>
              <p className="normal">GSTIN: <span className="bold">{toGstin}</span></p>
              <p className="normal">{toTrdName}</p>
              <p className="normal">:: Shipped From ::</p>
              <p className="normal">{toAddr1}, {toAddr2}, {toPlace}, {toPincode}</p>
            </div>
          </div>
        </div>

        <div className="border-box">
          <h2 className="goods-header">3. Goods Details</h2>
          <table className="table">
            <thead>
              <tr>
                <th>HSN</th>
                <th>Product & Desc.</th>
                <th>Quantity</th>
                <th>Taxable Amount</th>
                <th>Tax Rate (C+S+I+Cess)</th>
              </tr>
            </thead>
            <tbody>
              {itemList.map((item, index) => (
                <tr key={index}>
                  <td>{item.hsnCode}</td>
                  <td>{item.productName} & {item.productDesc}</td>
                  <td>{item.quantity} {item.qtyUnit}</td>
                  <td>{item.taxableAmount}</td>
                  <td>{item.sgstRate} + {item.cgstRate} + {item.igstRate} + {item.cessRate}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="border-box">
          <table className="table">
            <thead>
              <tr>
                <th>Tot. Taxable Amt</th>
                <th>CGST Amt</th>
                <th>SGST Amt</th>
                <th>IGST Amt</th>
                <th>CESS Amt</th>
                <th>CESS Non.Advol Amt</th>
                <th>Other Amt</th>
                <th>Total Inv. Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{totalValue}</td>
                <td>{cgstValue}</td>
                <td>{sgstValue}</td>
                <td>{igstValue}</td>
                <td>{cessValue}</td>
                <td>{cessNonAdvolValue}</td>
                <td>{otherValue}</td>
                <td>{totInvValue}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="border-box">
          <h2 className="transport-header">4. Transportation Details</h2>
          <div className="flex-row">
            <p className="normal">Transporter ID & Name: <span className="bold">{transporterId}, {transporterName}</span></p>
            <p className="normal">Transporter Doc. No & Date: <span className="bold">{transDocNo}, {transDocDate}</span></p>
          </div>
        </div>

        <div className="border-box">
          <h2 className="vehicle-header">5. Vehicle Details</h2>
          <table className="table">
            <thead>
              <tr>
                <th>Mode</th>
                <th>Vehicle / Trans Doc No & Dt.</th>
                <th>From</th>
                <th>Entered Date</th>
                <th>Entered By</th>
                <th>CEWB No. (if any)</th>
                <th>Multi Veh.Info (if any)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{transMode}</td>
                <td>{vehicleNo}</td>
                <td>{fromPlace}</td>
                <td>{billData.entered_date}</td>
                <td>{billData.entered_by}</td>
                <td>{billData.cewb_no}</td>
                <td>{billData.multi_vehicle_info}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="center">
          <Barcode value="123456789012" />
        </div>

        <p className="note">Note*: If there is any discrepancy in information please try again after sometime.</p>
      </div>
    </div>
  );
};

export default EWayBill;
